(function(window,document){"use strict";
function clean(v){return String(v==null?"":v).trim()}
function el(id){return document.getElementById(id)}
function set(id,v){const x=el(id);if(x)x.textContent=clean(v)}
function identity(){const q=new URLSearchParams(location.search);return clean(q.get("project")||q.get("project_code")||q.get("slug")||q.get("project_id"))}
function notFound(){set("projectTitle","Project not found");set("projectState","TESTNET • NOT FOUND");set("projectMeta","This project is not available in the Testnet registry.");set("projectDescription","The requested project could not be resolved against the approved Testnet project registry.");document.title="Project not found • ALBUKHR TESTNET"}
function render(p){const name=clean(p.name)||clean(p.title)||"Project",code=clean(p.project_code)||"—",type=clean(p.project_type).toUpperCase()||"—",slot=p.core_slot==null?"—":p.core_slot,status=clean(p.status).toUpperCase()||"APPROVED";set("projectTitle",name);set("projectState","TESTNET • "+status);set("projectMeta",type+" • Core Slot "+slot);set("projectDescription",clean(p.description)||"Registered ALBUKHR project available for controlled Testnet exploration.");set("projectCode",code);set("projectType",type);set("projectSlot",slot);set("projectNetwork",clean(p.network).toUpperCase()||"TESTNET");document.title=name+" • ALBUKHR TESTNET";const img=el("projectLogo"),fb=el("logoFallback");if(img&&clean(p.logo_url)){img.src=clean(p.logo_url);img.alt=name;img.hidden=false;if(fb)fb.hidden=true;img.onerror=function(){img.hidden=true;if(fb)fb.hidden=false}}else{if(img)img.hidden=true;if(fb)fb.hidden=false}}
async function load(){try{if(!window.AlbukhrEnvironment||!window.AlbukhrEnvironment.isKnown()||window.AlbukhrEnvironment.getNetwork()!=="testnet")throw Error("Invalid ALBUKHR environment.");if(!window.ALBUKHR_SUPABASE)throw Error("Testnet Supabase Core is unavailable.");if(!window.AlbukhrTestnetRegistry)throw Error("Testnet Project Registry module is unavailable.");const id=identity();if(!id)return notFound();await window.AlbukhrTestnetRegistry.load();const p=window.AlbukhrTestnetRegistry.resolve(id);p?render(p):notFound()}catch(e){console.error("[ALBUKHR TESTNET PROJECT]",e);set("projectState","TESTNET • UNAVAILABLE");set("projectMeta","Unable to load the Testnet project registry.");set("projectDescription","The Testnet project data could not be loaded. Please return to the Testnet home page and try again.")}}
function init(){const modal=el("infoModal");const close=()=>{if(modal)modal.hidden=true};const info=el("infoButton");if(info)info.onclick=()=>{if(modal)modal.hidden=false};if(el("closeInfo"))el("closeInfo").onclick=close;if(el("infoOk"))el("infoOk").onclick=close;if(modal)modal.onclick=e=>{if(e.target===modal)close()};const refresh=el("refreshBtn");if(refresh)refresh.onclick=async()=>{refresh.disabled=true;refresh.textContent="↻ Loading…";try{await window.AlbukhrTestnetRegistry.load(true);await load()}finally{refresh.disabled=false;refresh.textContent="↻ Refresh"}};load()}
document.readyState==="loading"?document.addEventListener("DOMContentLoaded",init,{once:true}):init();
})(window,document);
