/* ALBUKHR ADMIN AUTH — CONSOLIDATED v3.0 */
(function(w){"use strict";

function c(){return w.requireAlbukhrAdminSupabaseClient()}
async function adminLogin({email,accessKey}={}){try{email=String(email||"").trim().toLowerCase();accessKey=String(accessKey||"").trim();if(!email)return{success:false,error:"Administrator email is required."};if(!accessKey)return{success:false,error:"Access key is required."};const environment=w.getAlbukhrAdminEnvironment();const{data,error}=await c().auth.signInWithPassword({email,password:accessKey});if(error)return{success:false,error:error.message||"Invalid administrator credentials."};const user=data?.user,session=data?.session;if(!user?.id||!session){try{await c().auth.signOut()}catch(_){}return{success:false,error:"No valid admin session was returned."}}const{data:admin,error:ae}=await c().from("admin_users").select("*").eq("auth_user_id",user.id).eq("status","active").maybeSingle();if(ae)return{success:false,error:"Unable to verify administrator profile."};if(!admin)return{success:false,error:"Admin account not found or inactive."};const role=String(admin.role_code||"").trim().toLowerCase();if(!role)return{success:false,error:"Administrator role is not configured."};const{error:ue}=await c().from("admin_users").update({last_login:new Date().toISOString()}).eq("id",admin.id);if(ue)console.warn("[ADMIN AUTH] last_login update failed:",ue);if(typeof w.logAdminAction==="function")try{await w.logAdminAction({action:"login",target:"admin_auth",details:{username:admin.username||"",role,environment}})}catch(e){console.warn(e)}return{success:true,admin,user,session,environment,network:environment}}catch(e){console.error(e);return{success:false,error:e?.message||"Login failed."}}}
async function adminLogout(){try{let a=null;try{a=await w.getCurrentAdmin?.()}catch(_){}if(a&&w.logAdminAction)try{await w.logAdminAction({action:"logout",target:"admin_auth",details:{username:a.username||"",role:a.role_code||"",environment:w.getAlbukhrAdminEnvironment()}})}catch(_){}await c().auth.signOut()}catch(e){console.error("[ADMIN AUTH] Logout:",e)}finally{w.location.replace("admin-login.html")}}
w.adminLogin=adminLogin;w.adminLogout=adminLogout;

})(window);
